<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <Nullable>disable</Nullable>

    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>

    <RootNamespace>JasonLibrary.Tests</RootNamespace>
    <AssemblyName>JasonLibrary.Tests</AssemblyName>

    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>

    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />

    <PackageReference Include="MSTest.TestAdapter" Version="3.11.1" />

    <PackageReference Include="MSTest.TestFramework" Version="3.11.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\JasonLibrary\JasonLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\Text\Formatting\" />
  </ItemGroup>

</Project>