using JasonLibrary.Infrastructure.Enums;

namespace JasonLibrary.Providers.PostgreSql.Enums
{
    public enum PostgreSqlColumnTypeName
    {
        Unknown = 0,
        Boolean,
        [EnumAlias("boolean[]")]
        BooleanArray,
        Bytea,
        [EnumAlias("bytea[]")]
        ByteaArray,
        BigInt,
        [EnumAlias("bigint[]")]
        BigIntArray,
        SmallInt,
        [EnumAlias("smallint[]")]
        SmallIntArray,
        Text,
        [EnumAlias("text[]")]
        TextArray,
        Real,
        [EnumAlias("real[]")]
        RealArray,
        [EnumAlias("double precision")]
        DoublePrecision,
        [EnumAlias("double precision[]")]
        DoublePrecisionArray,
        [EnumAlias("\"char\"[]")]
        CharArray,
        [EnumAlias("integer[]")]
        IntegerArray,
        [EnumAlias("aclitem[]")]
        AclItemArray,
        [EnumAlias("cid[]")]
        CidArray,
        [EnumAlias("oid[]")]
        OidArray,
        OidVector,
        DateTime,
        [EnumAlias("date[]")]
        DateArray,
        UUID,
        [EnumAlias("uuid[]")]
        UUIDArray,
        Xml,
        [EnumAlias("xml[]")]
        XmlArray,
        [EnumAlias("xid[]")]
        XIDArray,
        [EnumAlias("xid8[]")]
        XID8Array,
        Box,
        [EnumAlias("box[]")]
        BoxArray,
        Cidr,
        [EnumAlias("cidr[]")]
        CidrArray,
        Circle,
        [EnumAlias("circle[]")]
        CircleArray,
        DateRange,
        [EnumAlias("daterange[]")]
        DateRangeArray,
        DateMultiRange,
        [EnumAlias("datemultirange[]")]
        DateMultiRangeArray,
        [EnumAlias("gtsvector[]")]
        GtsVectorArray,
        Inet,
        [EnumAlias("inet[]")]
        InetArray,
        Int2Vector,
        [EnumAlias("int2vector[]")]
        Int2VectorArray,
        Int4MultiRange,
        [EnumAlias("int4multirange[]")]
        Int4MultiRangeArray,
        Int8MultiRange,
        [EnumAlias("int8multirange[]")]
        Int8MultiRangeArray,
        Int4Range,
        [EnumAlias("int4range[]")]
        Int4RangeArray,
        Int8Range,
        [EnumAlias("int8range[]")]
        Int8RangeArray,
        Json,
        [EnumAlias("json[]")]
        JsonArray,
        Jsonb,
        [EnumAlias("jsonb[]")]
        JsonbArray,
        Line,
        [EnumAlias("line[]")]
        LineArray,
        Lseg,
        [EnumAlias("lseg[]")]
        LsegArray,
        MacAddr,
        [EnumAlias("macaddr[]")]
        MacAddrArray,
        MacAddr8,
        [EnumAlias("macaddr8[]")]
        MacAddr8Array,
        Money,
        [EnumAlias("money[]")]
        MoneyArray,
        [EnumAlias("name[]")]
        NameArray,
        NumMultiRange,
        [EnumAlias("nummultirange[]")]
        NumMultiRangeArray,
        NumRange,
        [EnumAlias("numrange[]")]
        NumRangeArray,
        [EnumAlias("oidvector[]")]
        OidVectorArray,
        [EnumAlias("pg_lsn[]")]
        PgLsnArray,
        Path,
        [EnumAlias("path[]")]
        PathArray,
        [EnumAlias("pg_snapshot[]")]
        PgSnapShotArray,
        Point,
        [EnumAlias("point[]")]
        PointArray,
        Polygon,
        [EnumAlias("polygon[]")]
        PolygonArray,
        RefCursor,
        [EnumAlias("refcursor[]")]
        RefCursorArray,
        [EnumAlias("regclass[]")]
        RegClassArray,
        [EnumAlias("regcollation[]")]
        RegCollationArray,
        [EnumAlias("regconfig[]")]
        RegConfigArray,
        [EnumAlias("regdictionary[]")]
        RegDictionaryArray,
        [EnumAlias("regnamespace[]")]
        RegNameSpaceArray,
        [EnumAlias("regoper[]")]
        RegOperArray,
        [EnumAlias("regoperator[]")]
        RegOperatorArray,
        [EnumAlias("regproc[]")]
        RegProcArray,
        [EnumAlias("regprocedure[]")]
        RegProcedureArray,
        [EnumAlias("regrole[]")]
        RegRoleArray,
        [EnumAlias("regtype[]")]
        RegTypeArray,
        [EnumAlias("tid[]")]
        TIDArray,
        [EnumAlias("tsquery[]")]
        TsQueryArray,
        TsRange,
        [EnumAlias("tsrange[]")]
        TsRangeArray,
        TstzRange,
        [EnumAlias("tstzrange[]")]
        TstzRangeArray,
        TstzMultiRange,
        [EnumAlias("tstzmultirange[]")]
        TstzMultiRangeArray,
        [EnumAlias("tsvector[]")]
        TsVectorArray,
        [EnumAlias("txid_snapshot[]")]
        TxIDSnapShotArray,
        TsMultiRange,
        [EnumAlias("tsmultirange[]")]
        TsMultiRangeArray,
        [EnumAlias("character varying[]")]
        CharacterVaryingArray,
        Character,
        [EnumAlias("character[]")]
        CharacterArray,
        Bit,
        [EnumAlias("bit[]")]
        BitArray,
        [EnumAlias("bit varying")]
        BitVarying,
        [EnumAlias("bit varying[]")]
        BitVaryingArray,
        Interval,
        [EnumAlias("interval[]")]
        IntervalArray,
        [EnumAlias("time with time zone")]
        TimeWithTimeZone,
        [EnumAlias("time with time zone[]")]
        TimeWithTimeZoneArray,
        [EnumAlias("time without time zone")]
        TimeWithoutTimeZone,
        [EnumAlias("time without time zone[]")]
        TimeWithoutTimeZoneArray,
        TimestampWithTimeZone,
        [EnumAlias("timestamp with time zone[]")]
        TimestampWithTimeZoneArray,
        TimestampWithoutTimeZone,
        [EnumAlias("timestamp without time zone[]")]
        TimestampWithoutTimeZoneArray,
        Numeric,
        [EnumAlias("numeric[]")]
        NumericArray,
        Integer
    }
}