using JasonQuery.Core.Database.CreateScript.SqlServer;
using JasonQuery.Core.Database.SqlBuilder.SqlServer.CreateScript.Table;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Data;

namespace JasonQuery.Tests.Core.Database.CreateScript.SqlServer
{
    [TestClass]
    public sealed class SqlServerTableCreateScriptVersionCompatibilityTests
    {
        [TestMethod]
        [TestCategory("Regression")]
        [TestCategory("CreateScript")]
        [TestCategory("SqlServer")]
        public void SqlServer2016_PrimaryKeyMetadataSql_DoesNotReferenceOptimizeColumn()
        {
            var request = CreateRequest(13);

            var sql = SqlServerTableCreateScriptSqlBuilder.BuildPrimaryKeyWithSql(request, "PK_CustomerInfo");

            AssertDoesNotContain(sql.ToLowerInvariant(), "i.optimize_for_sequential_key");
            Assert.Contains("CAST(0 AS bit) AS Optimize_For_Sequential_Key", sql);
        }

        [TestMethod]
        [TestCategory("Regression")]
        [TestCategory("CreateScript")]
        [TestCategory("SqlServer")]
        public void SqlServer2019_PrimaryKeyMetadataSql_ReferencesOptimizeColumn()
        {
            var request = CreateRequest(15);

            var sql = SqlServerTableCreateScriptSqlBuilder.BuildPrimaryKeyWithSql(request, "PK_CustomerInfo");

            Assert.Contains("i.optimize_for_sequential_key", sql.ToLowerInvariant());
            AssertDoesNotContain(sql, "CAST(0 AS bit) AS Optimize_For_Sequential_Key");
        }

        [TestMethod]
        [TestCategory("Regression")]
        [TestCategory("CreateScript")]
        [TestCategory("SqlServer")]
        public void SqlServer2016_CreateScript_DoesNotEmitOptimizeOption()
        {
            var request = CreateRequest(13);

            var script = SqlServerTableCreateScriptAssembler.Build
            (
                request,
                CreateMetadataExecutor(optimizeForSequentialKey: true)
            );

            Assert.Contains("ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON", script);
            AssertDoesNotContain(script, "OPTIMIZE_FOR_SEQUENTIAL_KEY");
        }

        [TestMethod]
        [TestCategory("Regression")]
        [TestCategory("CreateScript")]
        [TestCategory("SqlServer")]
        public void SqlServer2019_CreateScript_EmitsOptimizeOption()
        {
            var request = CreateRequest(15);

            var script = SqlServerTableCreateScriptAssembler.Build
            (
                request,
                CreateMetadataExecutor(optimizeForSequentialKey: true)
            );

            Assert.Contains("ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = ON", script);
        }

        private static SqlServerCreateScriptRequest CreateRequest(int sqlServerMajorVersion)
        {
            return SqlServerCreateScriptRequest.Create
            (
                schemaType: "Tables",
                schemaNode: "MyDB",
                schemaDbo: "dbo",
                schemaName: "CustomerInfo",
                objectID: "100",
                excludeNativeDatabase: false,
                dateTimeFormat: "yyyy/MM/dd HH:mm:ss",
                sqlServerMajorVersion: sqlServerMajorVersion
            );
        }

        private static Func<string, DataTable> CreateMetadataExecutor(bool optimizeForSequentialKey)
        {
            return sql =>
            {
                if (Contains(sql, "---Get Table Object Info"))
                {
                    return CreateObjectInfoTable();
                }

                if (Contains(sql, "---Get Table Constraint Info"))
                {
                    return CreateConstraintTable();
                }

                if (Contains(sql, "---Get Table Column Comments"))
                {
                    return new DataTable();
                }

                if (Contains(sql, "---Get Table Column Info"))
                {
                    return CreateColumnInfoTable();
                }

                if (Contains(sql, "---Get Table Primary Key Info"))
                {
                    return CreatePrimaryKeyOptionTable(optimizeForSequentialKey);
                }

                if (Contains(sql, "---Get Table Primary Key Column Order"))
                {
                    return CreatePrimaryKeyColumnOrderTable();
                }

                if (Contains(sql, "---Get Table Default Constraint Info") || Contains(sql, "---Get Table Comment Info") || Contains(sql, "---Get Table Non-Clustered Index Summary"))
                {
                    return new DataTable();
                }

                Assert.Fail($"Unexpected SQL generated by the assembler:\r\n{sql}");
                return null;
            };
        }

        private static bool Contains(string text, string value)
        {
            return (text ?? string.Empty).IndexOf(value, StringComparison.Ordinal) >= 0;
        }

        private static void AssertDoesNotContain(string text, string unexpectedValue)
        {
            Assert.IsFalse
            (
                Contains(text, unexpectedValue),
                $"Expected text not to contain '{unexpectedValue}', but it was found.\r\nActual text:\r\n{text}"
            );
        }

        private static DataTable CreateObjectInfoTable()
        {
            var table = new DataTable();

            table.Columns.Add("Object_ID", typeof(int));
            table.Columns.Add("Create_Date", typeof(DateTime));
            table.Columns.Add("Modify_Date", typeof(DateTime));

            table.Rows.Add
            (
                100,
                new DateTime(2026, 8, 5, 10, 0, 0),
                new DateTime(2026, 8, 5, 11, 0, 0)
            );

            return table;
        }

        private static DataTable CreateConstraintTable()
        {
            var table = new DataTable();

            table.Columns.Add("Column_Name", typeof(string));
            table.Columns.Add("Ordinal_Position", typeof(int));
            table.Columns.Add("Constraint_Name", typeof(string));
            table.Columns.Add("Constraint_Type", typeof(string));
            table.Columns.Add("Check_Clause", typeof(string));

            table.Rows.Add
            (
                "CustomerID",
                1,
                "PK_CustomerInfo",
                "PRIMARY KEY",
                DBNull.Value
            );

            return table;
        }

        private static DataTable CreateColumnInfoTable()
        {
            var table = new DataTable();

            table.Columns.Add("Column_Name", typeof(string));
            table.Columns.Add("Ordinal_Position", typeof(int));
            table.Columns.Add("Data_Type", typeof(string));
            table.Columns.Add("Is_Nullable", typeof(string));
            table.Columns.Add("Character_Maximum_Length", typeof(int));
            table.Columns.Add("Numeric_Precision", typeof(int));
            table.Columns.Add("Numeric_Scale", typeof(int));
            table.Columns.Add("DateTime_Precision", typeof(int));
            table.Columns.Add("Column_Default", typeof(string));

            table.Rows.Add
            (
                "CustomerID",
                1,
                "int",
                "NO",
                DBNull.Value,
                10,
                0,
                DBNull.Value,
                DBNull.Value
            );

            return table;
        }

        private static DataTable CreatePrimaryKeyOptionTable(bool optimizeForSequentialKey)
        {
            var table = new DataTable();

            table.Columns.Add("Is_Padded", typeof(bool));
            table.Columns.Add("No_Recompute", typeof(bool));
            table.Columns.Add("Ignore_Dup_Key", typeof(bool));
            table.Columns.Add("Allow_Row_Locks", typeof(bool));
            table.Columns.Add("Allow_Page_Locks", typeof(bool));
            table.Columns.Add("Optimize_For_Sequential_Key", typeof(bool));
            table.Columns.Add("GroupName", typeof(string));

            table.Rows.Add
            (
                false,
                false,
                false,
                true,
                true,
                optimizeForSequentialKey,
                "PRIMARY"
            );

            return table;
        }

        private static DataTable CreatePrimaryKeyColumnOrderTable()
        {
            var table = new DataTable();

            table.Columns.Add("Column_ID", typeof(int));
            table.Columns.Add("Is_Descending_Key", typeof(bool));

            table.Rows.Add(1, false);

            return table;
        }
    }
}
